### ISSUE TITLE
how do we identity different type of display? extract keyword and store inside object?

### ISSUE THREAD

**Issue by bubblegan** [cs2103jan2015-f13-2j/main#20]
eg. display urgent , display tomorrow task, display all.

**Comment by anisyusof-sc** [comment]
as for the design of validator, any "display" command will be interpreted and forwarded to logic. i think there is a need to create a Request object, that contains information such as type &  date, to be passed from Validator to Logic/Engine. 

the purpose of having date field in Request object is due to commands such as "display tomorrow task". the word "tomorrow",  or "next Sunday", "two days ago", "23/2/15" etc. can easily be resolved to a Date object by natty. please work on creating entitiy.Request and identify what are the possible field.

for the logic part, i believe we have to identify what are the common ones. some examples are "display urgent", "display [date]" etc. 

do take note that "display [date]  task" is equivalent to "display [date]". Validator might drop the word "task" before passing Request object to Engine, depending on our design.

**Comment by anisyusof-sc** [comment]
Also, do take note that we have different agenda view. by default would be Daily View for the above mentioned commands. there are Weekly & Monthly view, depending on the command.
